language: php
php:
  - 7.2
  - 7.3

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --no-interaction
script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
